### PR TITLE
add lower method to template func

### PR DESCRIPTION
**Pull request by Konboi**
I want to include build tag in generated file by yo.
Then I want to use of generatted file name in build tag.

So I add  lower method. refered to [here](https://github.com/mercari/yo/blob/master/generator/generator.go#L131).

### CODE REVIEW

**Comment by kazegusuri** [comment]
ah, wait. If you just want to use strings.ToLower(), I think you can use it in template. what's the problem?

**Comment by Konboi** [comment]
> I think you can use it in template. what's the problem?

Oh, really ??

**Comment by Konboi** [comment]
I tried to use strings.ToLower method in template but I can't use it. I might made mistake.

Could you show me a way or example ??

**Comment by kazegusuri** [comment]
ah, ok. got it. You use stings.ToLower at generation time, not runtime. Then yes, you need to register a function.

Please rename `lower` to `tolower`.

**Pull request merged**
